name: Dependencies check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-dependencies:
    name: Check waiting for dependency update
    runs-on: ubuntu-latest

    # Grant permission to write commit statuses
    permissions:
      statuses: write
      pull-requests: write
      contents: read
      repository-projects: write

    steps:
      - uses: actions/checkout@v4

      - name: Check dependencies
        id: check-dependencies
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            
            const InProgressVersionNames = ['-fix-', '-feat-', '-canary'];

            function searchForVersion(rootFolder, depth = 0) {
                if (depth >= 3) {
                    return;
                }
                const files = fs.readdirSync(rootFolder);
                return files.some((file) => {
                    if (file === '.git' || file === '.github') {
                        return;
                    }
            
                    const filePath = path.join(rootFolder, file);
            
                    if (fs.statSync(filePath).isDirectory()) {
                        return searchForVersion(filePath, depth + 1);
                    } else if (file === 'package.json') {
                        const content = fs.readFileSync(filePath, 'utf-8');
                        const packageJson = JSON.parse(content);
                        const excludedVersions = packageJson.allowedInProgressVersions || [];
            
                        return checkDependencies(packageJson.dependencies, excludedVersions) || checkDependencies(packageJson.devDependencies, excludedVersions);
                    }
                });
            }
            
            function checkDependencies(dependencies, excludedVersions) {
                if (!dependencies) {
                    return;
                }
            
                const dependenciesInProgress = Object.values(dependencies)
                    .filter((depVersion) => !excludedVersions.some((excluded) => excluded === depVersion))
                    .filter((depVersion) => InProgressVersionNames.some((name) => depVersion.includes(name)));
            
                if(dependenciesInProgress.length > 0) {
                    console.log('Found dependencies in progress: ', dependenciesInProgress);
                }
            
                return dependenciesInProgress.length > 0;
            }
            
            const found = searchForVersion('./');
            core.setOutput('has-dependency-in-progress', found.toString());

      - name: Add label
        if: steps.check-dependencies.outputs.has-dependency-in-progress == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
        run: gh pr edit ${{ github.event.pull_request.number }} --add-label "Waiting For Dependency Update"

      - name: Remove label
        if: steps.check-dependencies.outputs.has-dependency-in-progress == 'false'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
        run: gh pr edit ${{ github.event.pull_request.number }} --remove-label "Waiting For Dependency Update"

      - name: Fail on dependency in progress
        if: steps.check-dependencies.outputs.has-dependency-in-progress == 'true'
        run: |
          echo "::error::You have some dependencies in progress. Please update them before merging."
          echo "If you want to allow some in-progress versions, you can add them to the 'allowedInProgressVersions' array in your package.json file."
          echo "For example, in your package.json:"
          echo "\"allowedInProgressVersions\": [\"1.0.0-feat-some-feature\"]"
          exit 78
